# Generated by Django 5.0.6 on 2024-06-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="image",
            field=models.ImageField(
                default="defaultuser.jpeg",
                height_field=100,
                upload_to="chat/",
                width_field=100,
            ),
        ),
    ]
