# Generated by Django 5.0.6 on 2024-06-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatroom_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="image",
            field=models.ImageField(default="defaultuser.jpeg", upload_to="chat/"),
        ),
    ]
