# Generated by Django 5.0.6 on 2024-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='defaultUser.png', upload_to='UserProfile/'),
        ),
    ]
