# Generated by Django 5.0.6 on 2024-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='UserProfile/defaultUser.png', upload_to='UserProfile/'),
        ),
    ]
