# Generated by Django 5.0.6 on 2024-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='static/UserProfile/defaultUser.png', upload_to='static/UserProfile'),
        ),
    ]
